### ISSUE TITLE
feat: Return Value for load Function

### ISSUE THREAD

**Issue by tooooo1** [fepack/image#35]
The load function in the current codebase does not return any value. This design was fine for our initial use case, but we anticipate that returning the generated image elements could be beneficial as our requirements evolve.

This change provides greater flexibility and allows users of the load feature to follow up on loaded images as needed. For example, you might have a test that needs to check which source was actually loaded, and having a function that returns a generated Image element simplifies this check.

--

              If need to BREAKING CHANGE interface, I think before merging this Pull Request is best timing to change interface before add test code.

How about new Pull Request to change this load interface first if you agree my suggestion. What is your opinion

_Originally posted by @manudeli in https://github.com/fepack/image/pull/32#discussion_r1333393327_

**Comment by manudeli** [comment]
Suggestion in https://github.com/fepack/image/pull/32#discussion_r1333386757

```ts
const loaded = await load('./images/test', ['webp', 'png']); // first one is trying, but if not available webp, png is fallback

```
